image: wondermonger/ci-tools:v3.0.1

stages:
  - install
  - lint
  - test
  - build
  - deploy

install:
  except:
    - tags
  artifacts:
    paths:
      - node_modules/
  script: ci-node-install
  stage: install

outdated:
  except:
    - tags
  allow_failure: true
  script: ci-node-outdated
  stage: install

lint:
  except:
    - tags
  script: ci-node-lint
  stage: lint

unit:
  except:
    - tags
  script: ci-node-test unit
  stage: test

integration:
  except:
    - tags
  services:
    - redis:latest
  script: ci-node-test integration
  stage: test
  variables:
    REDIS_HOST: redis

coverage:
  except:
    - tags
  artifacts:
    paths:
      - coverage/
      - README.md
  coverage: /All files\s*\|\s*([\d\.]+)/
  script:
    - ci-node-test coverage
    - ci-git-readme-badge -b coverage
  stage: test

release:
  only:
    - master
  script:
    - ci-git-config
    - ci-git-readme-badge -b pipeline
    - ci-git-release -a README.md
  stage: deploy

publish:
  only:
    - tags
  script:
    - ci-node-config
    - ci-node-release
  stage: deploy
