.base-default: &base-default
  image: docker:latest
  services:
    - docker:dind

variables:
  TEST_TAG: test:latest

stages:
  - lint
  - build
  - post-build
  - deploy

before_script:
  - docker build -t "${TEST_TAG}" .

lint:
  <<: *base-default
  rules:
    - if: $CI_COMMIT_TAG == null
  script: docker run
    -v "${PWD}:${PWD}"
    -w "${PWD}"
    "${TEST_TAG}"
    /bin/bash -c "ci-shell-lint"
  stage: lint

build:
  <<: *base-default
  rules:
    - if: $CI_COMMIT_TAG == null
  artifacts:
    paths:
      - bin/
      - lib/
      - public/
      - README.md
  script: docker run
    -v "${PWD}:${PWD}"
    -w "${PWD}"
    "${TEST_TAG}"
    /bin/bash -c "./build.sh"
  stage: build

pages:
  <<: *base-default
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  artifacts:
    paths:
      - public/
  script: ":"
  stage: post-build

release:
  <<: *base-default
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script: docker run
    -e CI_COMMIT_REF_NAME
    -e CI_PROJECT_PATH
    -e GIT_USER_EMAIL
    -e GIT_USER_NAME
    -e SSH_PRIVATE_KEY
    -v "${PWD}:${PWD}"
    -w "${PWD}"
    "${TEST_TAG}"
    /bin/bash -c "ci-git-config && ci-git-release -t shell -a bin -a lib -a public -a README.md"
  stage: deploy

publish:
  <<: *base-default
  rules:
    - if: $CI_COMMIT_TAG != null
  script: docker run
    -e CI_COMMIT_TAG
    -e CI_PROJECT_NAME
    -e DOCKER_ORGANIZATION="${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}"
    -e DOCKER_PASSWORD="${CI_REGISTRY_PASSWORD}"
    -e DOCKER_REGISTRY="${CI_REGISTRY}"
    -e DOCKER_USERNAME="${CI_REGISTRY_USER}"
    -v "/var/run/docker.sock:/var/run/docker.sock"
    -v "${PWD}:${PWD}"
    -w "${PWD}"
    "${TEST_TAG}"
    /bin/bash -c "ci-docker-build && ci-docker-config && ci-docker-release"
  stage: deploy
