image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy

before_script:
  - docker build -t "${TEST_TAG}" .

lint:
  script: docker run
    -w "/opt/ci-tools"
    "${TEST_TAG}"
    /bin/bash -c "ci-shell-lint"
  stage: test

release:
  only:
    - master
  script: docker run
    -e CI_COMMIT_REF_NAME
    -e CI_PROJECT_PATH
    -e GIT_USER_EMAIL
    -e GIT_USER_NAME
    -e SSH_PRIVATE_KEY
    -w "/opt/ci-tools"
    "${TEST_TAG}"
    /bin/bash -c "ci-git-config && ci-git-shell-release"
  stage: deploy

publish:
  only:
    - tags
  script: docker run
    -e CI_COMMIT_TAG
    -e CI_PROJECT_NAME
    -e DOCKER_ORGANIZATION
    -e DOCKER_PASSWORD
    -e DOCKER_USERNAME
    -v "/var/run/docker.sock:/var/run/docker.sock"
    -w "/opt/ci-tools"
    "${TEST_TAG}"
    /bin/bash -c "ci-docker-build && ci-docker-login && ci-docker-push"
  stage: deploy

variables:
  TEST_TAG: test:latest
